/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedTradeIndexRouteImport } from './routes/_authenticated/trade/index'
import { Route as AuthenticatedMarketIndexRouteImport } from './routes/_authenticated/market/index'
import { Route as AuthenticatedTradeHistoryRouteImport } from './routes/_authenticated/trade/history'
import { Route as AuthenticatedInventoryProductsRouteImport } from './routes/_authenticated/inventory/products'
import { Route as AuthenticatedInventoryMaterialsRouteImport } from './routes/_authenticated/inventory/materials'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedTradeIndexRoute = AuthenticatedTradeIndexRouteImport.update({
  id: '/trade/',
  path: '/trade/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketIndexRoute =
  AuthenticatedMarketIndexRouteImport.update({
    id: '/market/',
    path: '/market/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTradeHistoryRoute =
  AuthenticatedTradeHistoryRouteImport.update({
    id: '/trade/history',
    path: '/trade/history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryProductsRoute =
  AuthenticatedInventoryProductsRouteImport.update({
    id: '/inventory/products',
    path: '/inventory/products',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryMaterialsRoute =
  AuthenticatedInventoryMaterialsRouteImport.update({
    id: '/inventory/materials',
    path: '/inventory/materials',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof AuthenticatedIndexRoute
  '/inventory/materials': typeof AuthenticatedInventoryMaterialsRoute
  '/inventory/products': typeof AuthenticatedInventoryProductsRoute
  '/trade/history': typeof AuthenticatedTradeHistoryRoute
  '/market': typeof AuthenticatedMarketIndexRoute
  '/trade': typeof AuthenticatedTradeIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof AuthenticatedIndexRoute
  '/inventory/materials': typeof AuthenticatedInventoryMaterialsRoute
  '/inventory/products': typeof AuthenticatedInventoryProductsRoute
  '/trade/history': typeof AuthenticatedTradeHistoryRoute
  '/market': typeof AuthenticatedMarketIndexRoute
  '/trade': typeof AuthenticatedTradeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/inventory/materials': typeof AuthenticatedInventoryMaterialsRoute
  '/_authenticated/inventory/products': typeof AuthenticatedInventoryProductsRoute
  '/_authenticated/trade/history': typeof AuthenticatedTradeHistoryRoute
  '/_authenticated/market/': typeof AuthenticatedMarketIndexRoute
  '/_authenticated/trade/': typeof AuthenticatedTradeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/'
    | '/inventory/materials'
    | '/inventory/products'
    | '/trade/history'
    | '/market'
    | '/trade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/'
    | '/inventory/materials'
    | '/inventory/products'
    | '/trade/history'
    | '/market'
    | '/trade'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_authenticated/'
    | '/_authenticated/inventory/materials'
    | '/_authenticated/inventory/products'
    | '/_authenticated/trade/history'
    | '/_authenticated/market/'
    | '/_authenticated/trade/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/trade/': {
      id: '/_authenticated/trade/'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof AuthenticatedTradeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/market/': {
      id: '/_authenticated/market/'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AuthenticatedMarketIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trade/history': {
      id: '/_authenticated/trade/history'
      path: '/trade/history'
      fullPath: '/trade/history'
      preLoaderRoute: typeof AuthenticatedTradeHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/products': {
      id: '/_authenticated/inventory/products'
      path: '/inventory/products'
      fullPath: '/inventory/products'
      preLoaderRoute: typeof AuthenticatedInventoryProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/materials': {
      id: '/_authenticated/inventory/materials'
      path: '/inventory/materials'
      fullPath: '/inventory/materials'
      preLoaderRoute: typeof AuthenticatedInventoryMaterialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedInventoryMaterialsRoute: typeof AuthenticatedInventoryMaterialsRoute
  AuthenticatedInventoryProductsRoute: typeof AuthenticatedInventoryProductsRoute
  AuthenticatedTradeHistoryRoute: typeof AuthenticatedTradeHistoryRoute
  AuthenticatedMarketIndexRoute: typeof AuthenticatedMarketIndexRoute
  AuthenticatedTradeIndexRoute: typeof AuthenticatedTradeIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedInventoryMaterialsRoute: AuthenticatedInventoryMaterialsRoute,
  AuthenticatedInventoryProductsRoute: AuthenticatedInventoryProductsRoute,
  AuthenticatedTradeHistoryRoute: AuthenticatedTradeHistoryRoute,
  AuthenticatedMarketIndexRoute: AuthenticatedMarketIndexRoute,
  AuthenticatedTradeIndexRoute: AuthenticatedTradeIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
